### ISSUE TITLE
Incompatible changes in `AtnaApi` and `AtnaApi.NetStandard`

### ISSUE THREAD

**Issue by daveMueller** [MohawkMEDIC/atnaapi#2]
Hi @justin-fyfe,

we are using this library for quite some time. Last year we migrated our application from `netfx` to `netcore` and thus needed to move to `AtnaApi.NetStandard`. We now detected that there is a change that leads to validation errors of the protocol. It looks like the order of the properties in `AuditMessage.cs` was changed which leads to this error. The validation tool we are using shows that the `EventIdentificationType` property moved to another location which isn't aligned anymore with the schema defined in the [RFC3881](https://datatracker.ietf.org/doc/html/rfc3881#section-6.1).

![Error-1](https://github.com/user-attachments/assets/0cc36b8c-71bd-465b-8f9e-3582c529d029)

Is there somehow a possibility that you release a new version of the `AtnaApi.NetStandard` nuget package? Or can you also open source the code for the `netcore` version so that we can do the fix on our own?

I would appreciate any help 🙏

**Comment by justin-fyfe** [comment]
The issue has been fixed and pushed as version 1.2.1 – the commit is here for reference: Updated ordering of XmlElements to match RFC-3881 ordering · ***@***.***<https://github.com/MohawkMEDIC/atnaapi/commit/182dfb81291c20032f26517f85827d8392539c9c>

-Justin

From: David Müller ***@***.***>
Sent: November 28, 2024 10:53 AM
To: MohawkMEDIC/atnaapi ***@***.***>
Cc: Justin Fyfe ***@***.***>; Mention ***@***.***>
Subject: [MohawkMEDIC/atnaapi] Incompatible changes in `AtnaApi` and `AtnaApi.NetStandard` (Issue #2)


Hi @justin-fyfe<https://github.com/justin-fyfe>,

we are using this library for quite some time. Last year we migrated our application from netfx to netcore and thus needed to move to AtnaApi.NetStandard. We now detected that there is a change that leads to validation errors of the protocol. It looks like the order of the properties in AuditMessage.cs was changed which leads to this error. The validation tool we are using shows that the EventIdentificationType property moved to another location which isn't aligned anymore with the schema defined in the RFC3881<https://datatracker.ietf.org/doc/html/rfc3881#section-6.1>.

Error-1.jpg (view on web)<https://github.com/user-attachments/assets/0cc36b8c-71bd-465b-8f9e-3582c529d029>

Is there somehow a possibility that you release a new version of the AtnaApi.NetStandard nuget package? Or can you also open source the code for the netcore version so that we can do the fix on our own?

I would appreciate any help 🙏

**Comment by daveMueller** [comment]
I can confirm that with the new version it is working. @justin-fyfe really appreciate your quick work on this, thanks a lot 🙏 . You are the best 💪 🔥 🚀.
